window.galleryImages = {
  "bodas": [
    "assets/images/gallery/bodas/BODA/1.jpg",
    "assets/images/gallery/bodas/BODA/10.jpg",
    "assets/images/gallery/bodas/BODA/11.JPG",
    "assets/images/gallery/bodas/BODA/12.jpg",
    "assets/images/gallery/bodas/BODA/13.JPG",
    "assets/images/gallery/bodas/BODA/14.jpg",
    "assets/images/gallery/bodas/BODA/15.jpg",
    "assets/images/gallery/bodas/BODA/16.JPG",
    "assets/images/gallery/bodas/BODA/18.jpg",
    "assets/images/gallery/bodas/BODA/19.jpg",
    "assets/images/gallery/bodas/BODA/2.JPG",
    "assets/images/gallery/bodas/BODA/20.JPG",
    "assets/images/gallery/bodas/BODA/21.jpg",
    "assets/images/gallery/bodas/BODA/22.jpg",
    "assets/images/gallery/bodas/BODA/23.jpg",
    "assets/images/gallery/bodas/BODA/24.jpg",
    "assets/images/gallery/bodas/BODA/25.jpg",
    "assets/images/gallery/bodas/BODA/26.jpg",
    "assets/images/gallery/bodas/BODA/27.jpg",
    "assets/images/gallery/bodas/BODA/28.jpg",
    "assets/images/gallery/bodas/BODA/29..JPG",
    "assets/images/gallery/bodas/BODA/3.jpg",
    "assets/images/gallery/bodas/BODA/30.jpg",
    "assets/images/gallery/bodas/BODA/31.jpg",
    "assets/images/gallery/bodas/BODA/32.JPG",
    "assets/images/gallery/bodas/BODA/33.JPG",
    "assets/images/gallery/bodas/BODA/34.jpg",
    "assets/images/gallery/bodas/BODA/35.jpg",
    "assets/images/gallery/bodas/BODA/36.JPG",
    "assets/images/gallery/bodas/BODA/37.jpg",
    "assets/images/gallery/bodas/BODA/39.jpg",
    "assets/images/gallery/bodas/BODA/4.jpg",
    "assets/images/gallery/bodas/BODA/40.jpg",
    "assets/images/gallery/bodas/BODA/41.jpg",
    "assets/images/gallery/bodas/BODA/42.jpg",
    "assets/images/gallery/bodas/BODA/43.jpg",
    "assets/images/gallery/bodas/BODA/44.jpg",
    "assets/images/gallery/bodas/BODA/5.jpg",
    "assets/images/gallery/bodas/BODA/6.jpg",
    "assets/images/gallery/bodas/BODA/7.jpg",
    "assets/images/gallery/bodas/BODA/8.jpg",
    "assets/images/gallery/bodas/BODA/9.jpg",
  ],
  "xv-anos": [
    "assets/images/gallery/xv-anos/15 años/1.jpg",
    "assets/images/gallery/xv-anos/15 años/10.jpg",
    "assets/images/gallery/xv-anos/15 años/11.jpg",
    "assets/images/gallery/xv-anos/15 años/12.jpg",
    "assets/images/gallery/xv-anos/15 años/13.JPG",
    "assets/images/gallery/xv-anos/15 años/14.JPG",
    "assets/images/gallery/xv-anos/15 años/15.JPG",
    "assets/images/gallery/xv-anos/15 años/16.JPG",
    "assets/images/gallery/xv-anos/15 años/16X20.jpg",
    "assets/images/gallery/xv-anos/15 años/17.JPG",
    "assets/images/gallery/xv-anos/15 años/18.JPG",
    "assets/images/gallery/xv-anos/15 años/20.JPG",
    "assets/images/gallery/xv-anos/15 años/21.JPG",
    "assets/images/gallery/xv-anos/15 años/22.JPG",
    "assets/images/gallery/xv-anos/15 años/23.JPG",
    "assets/images/gallery/xv-anos/15 años/24.JPG",
    "assets/images/gallery/xv-anos/15 años/25.JPG",
    "assets/images/gallery/xv-anos/15 años/27.jpg",
    "assets/images/gallery/xv-anos/15 años/28.jpg",
    "assets/images/gallery/xv-anos/15 años/29.jpg",
    "assets/images/gallery/xv-anos/15 años/3.jpg",
    "assets/images/gallery/xv-anos/15 años/30.jpg",
    "assets/images/gallery/xv-anos/15 años/31.JPG",
    "assets/images/gallery/xv-anos/15 años/32.jpg",
    "assets/images/gallery/xv-anos/15 años/33.jpg",
    "assets/images/gallery/xv-anos/15 años/34.JPG",
    "assets/images/gallery/xv-anos/15 años/35.JPG",
    "assets/images/gallery/xv-anos/15 años/36.JPG",
    "assets/images/gallery/xv-anos/15 años/37.JPG",
    "assets/images/gallery/xv-anos/15 años/38.jpg",
    "assets/images/gallery/xv-anos/15 años/39.JPG",
    "assets/images/gallery/xv-anos/15 años/4.jpg",
    "assets/images/gallery/xv-anos/15 años/40.JPG",
    "assets/images/gallery/xv-anos/15 años/41.JPG",
    "assets/images/gallery/xv-anos/15 años/42.jpg",
    "assets/images/gallery/xv-anos/15 años/43.jpg",
    "assets/images/gallery/xv-anos/15 años/44.jpg",
    "assets/images/gallery/xv-anos/15 años/45.jpg",
    "assets/images/gallery/xv-anos/15 años/46.jpg",
    "assets/images/gallery/xv-anos/15 años/7.JPG",
    "assets/images/gallery/xv-anos/15 años/8.JPG",
  ],
  "tres-anos": [
    "assets/images/gallery/tres-anos/3 años/1.JPG",
    "assets/images/gallery/tres-anos/3 años/10.jpg",
    "assets/images/gallery/tres-anos/3 años/11.JPG",
    "assets/images/gallery/tres-anos/3 años/12.jpg",
    "assets/images/gallery/tres-anos/3 años/13.JPG",
    "assets/images/gallery/tres-anos/3 años/14.JPG",
    "assets/images/gallery/tres-anos/3 años/15.JPG",
    "assets/images/gallery/tres-anos/3 años/16.jpg",
    "assets/images/gallery/tres-anos/3 años/17.jpg",
    "assets/images/gallery/tres-anos/3 años/18.jpg",
    "assets/images/gallery/tres-anos/3 años/19.jpg",
    "assets/images/gallery/tres-anos/3 años/2.jpg",
    "assets/images/gallery/tres-anos/3 años/20.jpg",
    "assets/images/gallery/tres-anos/3 años/21.JPG",
    "assets/images/gallery/tres-anos/3 años/22.JPG",
    "assets/images/gallery/tres-anos/3 años/23...jpg",
    "assets/images/gallery/tres-anos/3 años/23.JPG",
    "assets/images/gallery/tres-anos/3 años/24.JPG",
    "assets/images/gallery/tres-anos/3 años/25.JPG",
    "assets/images/gallery/tres-anos/3 años/26.JPG",
    "assets/images/gallery/tres-anos/3 años/27.JPG",
    "assets/images/gallery/tres-anos/3 años/28.jpg",
    "assets/images/gallery/tres-anos/3 años/29.jpg",
    "assets/images/gallery/tres-anos/3 años/3.jpg",
    "assets/images/gallery/tres-anos/3 años/30.jpg",
    "assets/images/gallery/tres-anos/3 años/4.JPG",
    "assets/images/gallery/tres-anos/3 años/5.JPG",
    "assets/images/gallery/tres-anos/3 años/6.JPG",
    "assets/images/gallery/tres-anos/3 años/7.JPG",
    "assets/images/gallery/tres-anos/3 años/8.JPG",
    "assets/images/gallery/tres-anos/3 años/9.JPG",
  ],
  "bautizo": [
    "assets/images/gallery/bautizo/Bautizo/1.JPG",
    "assets/images/gallery/bautizo/Bautizo/10.JPG",
    "assets/images/gallery/bautizo/Bautizo/11.JPG",
    "assets/images/gallery/bautizo/Bautizo/12.JPG",
    "assets/images/gallery/bautizo/Bautizo/13.jpeg",
    "assets/images/gallery/bautizo/Bautizo/14.jpeg",
    "assets/images/gallery/bautizo/Bautizo/2.JPG",
    "assets/images/gallery/bautizo/Bautizo/3.JPG",
    "assets/images/gallery/bautizo/Bautizo/5.JPG",
    "assets/images/gallery/bautizo/Bautizo/6.JPG",
    "assets/images/gallery/bautizo/Bautizo/7.jpg",
    "assets/images/gallery/bautizo/Bautizo/8.JPG",
    "assets/images/gallery/bautizo/Bautizo/9.JPG",
  ],
  "newborn": [
    "assets/images/gallery/newborn/Sesión newborn/1.jpg",
    "assets/images/gallery/newborn/Sesión newborn/10.JPG",
    "assets/images/gallery/newborn/Sesión newborn/11.jpg",
    "assets/images/gallery/newborn/Sesión newborn/12.jpg",
    "assets/images/gallery/newborn/Sesión newborn/13.JPG",
    "assets/images/gallery/newborn/Sesión newborn/14.jpg",
    "assets/images/gallery/newborn/Sesión newborn/15.jpg",
    "assets/images/gallery/newborn/Sesión newborn/16.jpg",
    "assets/images/gallery/newborn/Sesión newborn/17.jpg",
    "assets/images/gallery/newborn/Sesión newborn/18.jpg",
    "assets/images/gallery/newborn/Sesión newborn/19.jpg",
    "assets/images/gallery/newborn/Sesión newborn/2.jpg",
    "assets/images/gallery/newborn/Sesión newborn/3.jpg",
    "assets/images/gallery/newborn/Sesión newborn/4.jpg",
    "assets/images/gallery/newborn/Sesión newborn/5.jpg",
    "assets/images/gallery/newborn/Sesión newborn/6.jpg",
    "assets/images/gallery/newborn/Sesión newborn/7.jpg",
    "assets/images/gallery/newborn/Sesión newborn/8.jpg",
    "assets/images/gallery/newborn/Sesión newborn/9.jpg",
  ],
};
